from __future__ import annotations

import argparse
import os
import platform
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = ROOT.parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from svh_dp.benchmarks.calvin_backend import build_calvin_probe
from svh_dp.config import load_config
from svh_dp.utils.common import ensure_dir, write_json


README_TEMPLATE = """# CALVIN Workspace Drop

Place a project-local CALVIN code drop under this directory so the workspace can
bootstrap CALVIN without relying on a globally installed environment.

Expected result after a valid drop:

- `calvin_env` becomes importable when `PYTHONPATH` is prefixed with the code-drop root
- `calvin_models` becomes importable under the same prefix

Typical layouts that can work:

- `<drop_root>/calvin_env/`
- `<drop_root>/calvin_models/`
- `<drop_root>/<repo_subdir>/calvin_env/`
- `<drop_root>/<repo_subdir>/calvin_models/`

After copying the code into this workspace, run:

```bash
python Experiment/core_code/scripts/bootstrap_calvin_workspace.py
python Experiment/core_code/scripts/diagnose_calvin_env.py
python Experiment/core_code/scripts/check_benchmark_backends.py
```
"""


def _activation_paths(base_path: Path) -> tuple[Path, Path]:
    shell_path = base_path
    powershell_path = base_path.with_suffix(".ps1")
    return shell_path, powershell_path


def _shell_pythonpath(entries: list[str]) -> str:
    return ":".join(entries)


def _powershell_pythonpath(entries: list[str]) -> str:
    return ";".join(entries)


def _build_config(config_path: Path) -> dict:
    config = load_config(config_path).data
    calvin_cfg = dict(config["benchmarks"]["calvin"])
    calvin_cfg["probe"] = dict(calvin_cfg["probe"])
    calvin_cfg["probe"]["project_root"] = str(PROJECT_ROOT)
    return calvin_cfg


def _resolve_preferred_root(calvin_cfg: dict) -> Path:
    preferred_root = calvin_cfg["workspace"]["preferred_root"]
    path = Path(preferred_root)
    if not path.is_absolute():
        path = PROJECT_ROOT / path
    path = path.resolve()
    if PROJECT_ROOT != path and PROJECT_ROOT not in path.parents:
        raise ValueError(f"preferred_root must remain inside the project: {path}")
    return path


def _resolve_activation_script_path(calvin_cfg: dict) -> Path:
    activation_script_path = calvin_cfg["workspace"]["activation_script_path"]
    path = Path(activation_script_path)
    if not path.is_absolute():
        path = PROJECT_ROOT / path
    path = path.resolve()
    if PROJECT_ROOT != path and PROJECT_ROOT not in path.parents:
        raise ValueError(
            f"activation_script_path must remain inside the project: {path}"
        )
    return path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        default=str(ROOT / "config" / "default.yaml"),
        help="Path to YAML config.",
    )
    parser.add_argument(
        "--source-root",
        help="Optional project-local code-drop root to validate in addition to the configured preferred root.",
    )
    parser.add_argument(
        "--output",
        help="Optional output path for the bootstrap manifest.",
    )
    args = parser.parse_args()

    calvin_cfg = _build_config(Path(args.config))
    preferred_root = _resolve_preferred_root(calvin_cfg)
    activation_script_path = _resolve_activation_script_path(calvin_cfg)
    shell_activation_path, powershell_activation_path = _activation_paths(
        activation_script_path
    )
    ensure_dir(preferred_root)
    ensure_dir(shell_activation_path.parent)
    readme_path = preferred_root / "README.md"
    if not readme_path.exists():
        readme_path.write_text(README_TEMPLATE, encoding="utf-8")

    search_roots = list(calvin_cfg["probe"].get("search_roots", []))
    preferred_root_str = str(preferred_root)
    if preferred_root_str not in search_roots:
        search_roots.insert(0, preferred_root_str)

    resolved_source_root = None
    if args.source_root:
        source_root = Path(args.source_root)
        if not source_root.is_absolute():
            source_root = PROJECT_ROOT / source_root
        source_root = source_root.resolve()
        if PROJECT_ROOT != source_root and PROJECT_ROOT not in source_root.parents:
            raise ValueError(f"source_root must remain inside the project: {source_root}")
        resolved_source_root = str(source_root)
        if resolved_source_root not in search_roots:
            search_roots.insert(0, resolved_source_root)

    calvin_cfg["probe"]["search_roots"] = search_roots
    probe = build_calvin_probe(calvin_cfg)
    shell_activation_lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by bootstrap_calvin_workspace.py",
    ]
    powershell_activation_lines = [
        "# Auto-generated by bootstrap_calvin_workspace.py",
    ]
    if probe["bootstrap_root"] is None:
        shell_activation_lines.append(
            "# No valid CALVIN bootstrap root is available yet. "
            "Copy a valid CALVIN code drop into the preferred workspace root and rerun the bootstrap helper."
        )
        powershell_activation_lines.append(
            "# No valid CALVIN bootstrap root is available yet. Copy a valid CALVIN "
            "code drop into the preferred workspace root and rerun the bootstrap helper."
        )
    else:
        pythonpath_entries = probe.get("pythonpath_entries", [probe["bootstrap_root"]])
        shell_activation_lines.extend(
            [
                f'export CALVIN_WORKSPACE_ROOT="{probe["bootstrap_root"]}"',
                f'export CALVIN_WORKSPACE_PYTHONPATH="{_shell_pythonpath(pythonpath_entries)}"',
                'export PYTHONPATH="${CALVIN_WORKSPACE_PYTHONPATH}${PYTHONPATH:+:${PYTHONPATH}}"',
            ]
        )
        powershell_activation_lines.extend(
            [
                f'$env:CALVIN_WORKSPACE_ROOT = "{probe["bootstrap_root"]}"',
                f'$env:CALVIN_WORKSPACE_PYTHONPATH = "{_powershell_pythonpath(pythonpath_entries)}"',
                (
                    'if ($env:PYTHONPATH) { '
                    '$env:PYTHONPATH = "$env:CALVIN_WORKSPACE_PYTHONPATH;$env:PYTHONPATH" '
                    '} else { '
                    '$env:PYTHONPATH = $env:CALVIN_WORKSPACE_PYTHONPATH '
                    '}'
                ),
            ]
        )
        if probe["dependency_blockers"]:
            shell_activation_lines.append(
                "# Runtime imports still require additional Python dependencies: "
                + ", ".join(probe["dependency_blockers"])
            )
            powershell_activation_lines.append(
                "# Runtime imports still require additional Python dependencies: "
                + ", ".join(probe["dependency_blockers"])
            )
    shell_activation_path.write_text(
        "\n".join(shell_activation_lines) + "\n",
        encoding="utf-8",
    )
    powershell_activation_path.write_text(
        "\n".join(powershell_activation_lines) + "\n",
        encoding="utf-8",
    )

    suggested_activation_command = (
        f". {powershell_activation_path}"
        if os.name == "nt"
        else f"source {shell_activation_path}"
    )
    suggested_pythonpath = None
    if probe["pythonpath_entries"]:
        joined_pythonpath = (
            _powershell_pythonpath(probe["pythonpath_entries"])
            if os.name == "nt"
            else _shell_pythonpath(probe["pythonpath_entries"])
        )
        suggested_pythonpath = (
            f"$env:PYTHONPATH=\"{joined_pythonpath};$env:PYTHONPATH\""
            if os.name == "nt"
            else f"PYTHONPATH={joined_pythonpath}:$PYTHONPATH"
        )

    payload = {
        "python_executable": sys.executable,
        "platform": platform.platform(),
        "preferred_root": preferred_root_str,
        "preferred_root_exists": preferred_root.exists(),
        "preferred_root_readme": str(readme_path),
        "source_root": resolved_source_root,
        "search_roots": probe["search_roots"],
        "activation_script_path": str(shell_activation_path),
        "activation_powershell_script_path": str(powershell_activation_path),
        "available": probe["available"],
        "bootstrap_available": probe["bootstrap_available"],
        "source_layout_available": probe["source_layout_available"],
        "bootstrap_root": probe["bootstrap_root"],
        "pythonpath_entries": probe["pythonpath_entries"],
        "dependency_blockers": probe["dependency_blockers"],
        "smoke_dependency_blockers": probe["smoke_dependency_blockers"],
        "module_probe": probe["module_probe"],
        "module_status": probe["module_status"],
        "runtime_ready": probe["runtime_ready"],
        "smoke_imports": probe["smoke_imports"],
        "smoke_status": probe["smoke_status"],
        "workspace_candidates": probe["workspace_candidates"],
        "message": probe["message"],
        "diagnosis": probe["diagnosis"],
        "suggested_pythonpath": suggested_pythonpath,
        "suggested_source_command": suggested_activation_command,
    }

    log_dir = ensure_dir(ROOT / "logs")
    output_path = Path(args.output) if args.output else log_dir / "calvin_workspace_bootstrap.json"
    if not output_path.is_absolute():
        output_path = PROJECT_ROOT / output_path
    write_json(output_path, payload)
    print(f"saved_bootstrap_manifest={output_path}")
    print(payload)


if __name__ == "__main__":
    main()
